DROP DATABASE IF EXISTS PERCYPHONE;
CREATE DATABASE PERCYPHONE;
USE PERCYPHONE;

DROP TABLE IF EXISTS `PRODUCT`;

CREATE TABLE `PRODUCT` (
    `product_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `price` DECIMAL(10, 2) NOT NULL,
    `stock` INT DEFAULT 0
)

DROP TABLE IF EXISTS `ADMIN`;

CREATE TABLE `ADMIN` (
    `admin_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `first name` VARCHAR(50) NOT NULL,
    `last name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
)